### ISSUE TITLE
MANIFEST FILE

### ISSUE THREAD

**Issue by amanharitsh123** [cristian99garcia/gmail-activity#24]
As Per the sugar activity guide lines I think we need to add a manifest file.

**Comment by amanharitsh123** [comment]
Manifest file is no longer included in bundles.

**Comment by quozl** [comment]
Was there some place you found old documentation?  We'd like to fix that.

**Comment by amanharitsh123** [comment]
I have found a create activity guide . Here it goes :
http://write.flossmanuals.net/make-your-own-sugar-activities/introduction/
it is on this page : https://developer.sugarlabs.org/desktop-activity.md.html

**Comment by quozl** [comment]
Thanks.  I looked but could not find a reference to MANIFEST.  Do you remember where it was?

**Comment by amanharitsh123** [comment]
ohh , actually i have downloaded the pdf version of this manual from here https://archive.org/details/MakeYourOwnSugarActivities
Looks like the "creating manifest file" section has been removed from the live floassmanuals documentation.

**Comment by quozl** [comment]
Thanks.  @jdsimmons might be able to fix that.
