### ISSUE TITLE
Has no license metadata

### ISSUE THREAD

**Issue by quozl** [cristian99garcia/gmail-activity#25]
A `license` is not in metadata file `activity/activity.info`

* [X] review licenses of components in bundle, (see below),
* [ ] rename LICENSE as COPYING,
* [ ] add back deleted LICENSE in uritemplate,
* [ ] add multiple-license-scenario metadata to activity.info.

Licenses of components in bundle;

* GPLv3 in LICENSE,
* GPLv3+ for top level *.py,
* Apache 2.0 for googleapiclient,
* MIT for httplib2, oauth2client, and urllib3,
* Modified BSD or Apache 2.0 for uritemplate, but LICENSE file is missing.

**Comment by chimosky** [comment]
Changes made in #26 
- [x]  rename LICENSE as COPYING,
- [x]  add back deleted LICENSE in uritemplate,
- [x]  add back deleted LICENSE in uritemplate,
- [x]  add multiple-license-scenario metadata to activity.info.

**Comment by chimosky** [comment]
Changes made in #26 
- [x]  rename LICENSE as COPYING,
- [x]  add back deleted LICENSE in uritemplate,
- [x]  add back deleted LICENSE in uritemplate,
- [x]  add multiple-license-scenario metadata to activity.info.
